---
name: ci
on:
  push:
    tags:
      - '*'
jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      -
        name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      -
        name: Get tag
        id: get_tag
        run: echo "tag=$(git describe --tags HEAD)" >> $GITHUB_OUTPUT
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ github.repository }}
      -
        name: Login to DH
        uses: docker/login-action@v3
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.DHT }}
      -
        name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHT }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64, linux/arm64, linux/arm/v7, linux/arm/v8
          push: true
          tags: |
            ${{ github.repository }}:${{ steps.get_tag.outputs.tag }},
            ${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:${{ steps.get_tag.outputs.tag }},
            ghcr.io/${{ github.repository }}:latest
          labels: ${{ steps.meta.outputs.labels }}
