---
name: Coveralls
on:
  push:
    branches:
      - master
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
#        os: [ ubuntu-latest, windows-latest, macos-latest ]
        os: [ ubuntu-latest ]
        python-version: [
#          "3.9",
#          "3.10",
          "3.11",
        ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python ${{matrix.python-version}}
        uses: actions/setup-python@v4
        with:
          python-version: ${{matrix.python-version}}
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r app/requirements.txt
          pip install pytest
          pip install pytest-cov
      - name: Coveralls
        uses: coverallsapp/github-action@master
        run: |
          pytest --cov=app --cov-report lcov
        with:
            github-token: ${{ secrets.GHT }}
            path-to-lcov: coverage.lcov
