---
name: Coveralls
on:
  push:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          pip install -r app/requirements.txt
          pip install pytest
          pip install pytest-cov
          pip install coveralls
      - name: Collect coverage data
        with:
          pytest_addopts: "--durations=0"
        run: |
          pytest --cov app --cov-append .
      - name: Report coverage to coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GHT }}
          path-to-lcov: coverage.xml
        run: |
          coveralls --service=github