---
name: Coveralls
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          python -m venv env
          source env/bin/activate
          pip install -r app/requirements.txt
          pip install coverage coveralls
      - name: Collect coverage data
        run: |
          coverage run --source=app -m unittest discover
      - name: Report coverage to coveralls
        uses: coverallsapp/github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GHT }}
