---
name: YAMLlint
on:
  - push
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
      - name: 'Yamllint'
        uses: ibiqlik/action-yamllint@v3
        with:
          file_or_dir: .github/workflows/
